language: python

matrix:
  include:
  - python: 3.5
    env: export FAIL_ON_EXTERNAL_DEPRECATION='False'
  - python: 3.5
    env: export FAIL_ON_EXTERNAL_DEPRECATION='True'
  - os: osx
    language: generic
    python: 3.5
    env: export FAIL_ON_EXTERNAL_DEPRECATION='False'
  allow_failures:
  - env: export FAIL_ON_EXTERNAL_DEPRECATION='True'

before_install:
- if [[ $TRAVIS_OS_NAME == 'osx' ]] ; then curl "https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh" -o miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
- chmod +x miniconda.sh
- "./miniconda.sh -b -p $HOME/miniconda"
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda update --yes conda

install:
  - DEPS="nose numpy scipy matplotlib ipython h5py sympy scikit-learn dill natsort setuptools scikit-image cython"
  - conda create -n testenv --yes $DEPS
  - source activate testenv
  - conda install pip
  - pip install coverage coveralls traits traitsui request tqdm
  - python setup.py install

script:
  - python setup.py build_ext --inplace
  - python continuous_integration/nosetest.py --with-coverage hyperspy

after_success:
- coveralls
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then python setup.py bdist_wheel; else python setup.py sdist; fi

before_deploy:
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then export DISTRIB=$(ls ./dist/*.whl); else export DISTRIB=$(ls ./dist/*.tar.gz); fi

deploy:
  provider: releases
  api_key:
    #sem-geologist:
    secure: n1CcuRSDf9GxJBFYr5GXGAhYL+sY1If1IzgMVY0YeeS4zHvIgn4DWf32iE+k/7GN6EsS59scVagg5zbDsO+DxVvYFT4BkqvBKz7SoHo1TMX7oqCHlwi+RnnUUBqeBCuq8zC7x9IPtfoLPXoFeUiGeYoAWcB+iPKrUIoWkBdAGi0fEl7b8K8JAn9kVF5xoqe4V4Bwcxnd2fTD2eI7JeA+mcRabGO53ERfZiJZqx9Do7YBKSG31E6IVcUCoehc2VFvTKwA7yzEXvPWyrmrKlRdYWjyLHRk+wDflHWkvzXGcr/6hewgxI5KjJ6eERWKZ9PqxukGr5G4lixMUlfgtNSxbnqyvBN7L0lGwpMBpT9XIjwaikcHd0bUgP6W8hNFP9OFVcrmMdYil7ko5OIZTw3Dc27RH6mLr/653hgvCDPg+GO/wfx0mVGAvn+vl7u0i/kfH0sMjvBKWmy3CEyt3jbrrawXwZa1wPgcCEwt/7f3WgiMEOOiZMrVQbB1QtLOXFi6KXr0gCKS3mShr3cmr4r6p6Xi95zNLQ0IM/B+mC3+/a8g1fDFYOJjzxlbQjn9WEV5Bzj8iw/VLx1ndnE2BE1A7bvk+yWKb1WiGP8n60OudQpHU5yrtwWCbrjUCl1PoYvB1zrZClAAFTr7/oxQRRACZ80ipYhSOSGC0FWPWSJ/gVs=
  file: "${DISTRIB}"
  skip_cleanup: true
  on:
    tags: true
